# Generated by Django 2.0.3 on 2018-07-17 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.PositiveIntegerField(verbose_name='設定金額')),
                ('payment', models.PositiveIntegerField(verbose_name='入金額')),
                ('balance', models.PositiveIntegerField(verbose_name='残高')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
            ],
        ),
    ]
