# Generated by Django 2.0.3 on 2018-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_auto_20180728_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(default='', verbose_name='入金額'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='balance',
            field=models.IntegerField(default='', verbose_name='残高'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
