# Generated by Django 2.0.3 on 2018-07-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_auto_20180718_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='aim',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
