# Generated by Django 2.0.3 on 2018-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_auto_20180728_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='aim',
            field=models.IntegerField(default='', verbose_name='設定金額'),
        ),
    ]
