# Generated by Django 2.0.3 on 2018-07-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_auto_20180729_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.IntegerField(default='', verbose_name='設定金額')),
            ],
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='amount',
            new_name='sent',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='aim',
        ),
    ]
