# Generated by Django 2.0.3 on 2018-07-29 02:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_auto_20180729_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aim',
            old_name='aim',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='deposit',
            name='aim',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='deposit.Aim', verbose_name='設定'),
            preserve_default=False,
        ),
    ]
