# Generated by Django 2.0.3 on 2018-07-29 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0007_auto_20180729_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='aim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='deposit.Aim', verbose_name='設定'),
        ),
    ]
