# Generated by Django 2.0.3 on 2018-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_auto_20180728_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(default='', verbose_name='入金額'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='balance',
            field=models.IntegerField(default='', verbose_name='残高'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='aim',
            field=models.IntegerField(default='', verbose_name='設定金額'),
        ),
    ]
