# Generated by Django 2.0.3 on 2018-07-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_auto_20180728_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
